demo/config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :events do
    collection do
      get :search
      post :search
    end

    member do
      get :dashboard
    end
  end

  resources :events do
    resource :state, :controller => 'event_states'
    resources :attendees, :controller => 'event_attendees'
    resource :location, :controller => 'event_locations'
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  root :to => "welcome#index"

  #So the below routing helper will be admin_events_path or admin_event_path(event)
  namespace :admin do
    resources :events
  end
end

demo/app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :find_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build( attendee_params )
    if @attendee.save
      redirect_to event_attendees_url( @event )
    else
      render :action => :new
    end
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.find(params[:id])
    if @attendee.update(attendee_params)
      redirect_to event_attendees_url(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy
    redirect_to event_attendees_url(@event)
  end

  protected

  def find_event
    @event = Event.find(params[:event_id])
  end

  def attendee_params
    params.require(:attendee).permit(:name)
  end
end

demo/app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

demo/app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event,
  @attendee), :html => { :method => :patch } do |f|%>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

demo/app/views/event_attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>
    <li>
      <%= attendee.name %>
      <%= link_to 'show', event_attendee_path(@event, attendee) %>
      <%= link_to 'edit', edit_event_attendee_path(@event, attendee) %>
      <%= link_to 'destroy', event_attendee_path(@event, attendee),
  :method => :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'new attendee', new_event_attendee_path(@event) %>

demo/app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

demo/app/views/event_attendees/show.html.erb
<p>
  <%= @attendee.name %>
</p>