demo/config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :events do
    collection do
      get :search
      post :search
    end

    member do
      get :dashboard
    end
  end

  resources :events do
    resource :state, :controller => 'event_states'
    resources :attendees, :controller => 'event_attendees'
    resource :location, :controller => 'event_locations'
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  root :to => "welcome#index"

  #So the below routing helper will be admin_events_path or admin_event_path(event)
  namespace :admin do
    resources :events
  end
end

demo/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category
  has_many :attendees
  has_many :event_groupships
  has_many :groups, :through => :event_groupships

  has_one :location
  accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if => :all_blank

  validates_presence_of :name
  delegate :name, :to => :category, :prefix => true, :allow_nil => true
  delegate :name, :to => :location, :prefix => true, :allow_nil => true

  def closed?
    self.status == "CLOSED"
  end

  def open?
    !self.closed?
  end

  def open!
    self.status = "OPEN"
    self.save!
  end

  def close!
    self.status = "CLOSED"
    self.save!
  end
end

demo/app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate
  layout "admin"

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == "username" && password == "password"
    end
  end

end

demo/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :only => [:show, :edit, :update, :destroy, :dashboard]

  def index
    sort_by = (params[:order] == 'name') ? 'name' : 'created_at'
    @events = Event.order(sort_by).page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.xml {render :xml => @events.to_xml }
      format.json {render :json => @events.to_json }
      format.atom { @feed_title = "My event list" } #index.atom.builder
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "event was successfully created"
      redirect_to events_url
    else
      render :action => :new
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html { @page_title = @event.name } # show.html.erb
      format.xml # show.xml.builder
      format.json { render :json => { id: @event.id, name: @event.name, category: @event.category, location: @event.location  }.to_json }
    end
  end

  def edit
  end

  def update
    Rails.logger.debug("event:\t #{@event_params}")
    if @event.update(event_params)
      flash[:notice] = "event was successfully updated"
      redirect_to event_url(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "event was successfully deleted"

    redirect_to :action => :index
  end

  def search
    @events = Event.where( ["name like ?", "%#{params[:keyword]}%"] ).page(params[:page]).per(5)
    render :action => :index
  end

  def dashboard
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :category_id, \
                                  :location_attributes => [:name, :_destroy, :id], \
                                  :group_ids => [] )
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

demo/app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

demo/app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event)
    event.build_location unless event.location
    event
  end
end

demo/app/views/events/.#show.html.erb
root@ip-172-31-43-197.us-west-2.compute.internal.6504:1416688507

demo/app/views/events/_form.html.erb
<%= f.input :name, :label => "Event Name" %>
<%= f.input :description, :as => :text, :label => "Description" %>
<%= f.association :category, :label => "Category" %>
<%= f.association :groups, :as => :check_boxes, :label => "Groups" %>
<% if @event.errors.any? %>
  <ul>
    <% @event.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= f.fields_for :location do |location_form| %>
  <p>
    <%= location_form.label :name, "Location Name" %>
    <%= location_form.text_field :name %>

    <% unless location_form.object.new_record? %>
      <%= location_form.label :_destroy, 'Remove:' %>
      <%= location_form.check_box :_destroy %>
    <% end %>
  </p>
<% end %>

demo/app/views/events/edit.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= simple_form_for setup_event(@event), :url => event_path(@event),
  :method => :put do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <%= f.submit "Update" %>
  <% end %>
<% end %>

demo/app/views/events/index.html.erb
<%= form_tag search_events_path :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>
<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %>
      <%= link_to '(XML)', event_path(event, :format => :xml) %>
      <%= link_to '(JSON)', event_path(event, :format => :json) %>
      <%= link_to 'Edit', edit_event_path(event) %>
      <%= button_to 'Delete', event_path(event), :method => :delete %>
      <%= link_to 'attendees', event_attendees_path(event) %>
      <%= link_to 'location', event_location_path(event) %>
      <%= link_to 'Dashboard', dashboard_event_path(event)%>
    </li>
  <% end %>
</ul>
<%= link_to 'New Event', new_event_path %>
<%= link_to 'Atom feed', events_path(:format => :atom) %>
<%= link_to 'Sort by Name', events_path(:order => 'name') %>
<%= link_to 'Sort by Default', events_path %>
<%= paginate @events %>

demo/app/views/events/new.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= simple_form_for setup_event(@event), :url => events_path do |f|%>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <%= f.submit "Create" %>
  <% end %>
 <% end %>

demo/app/views/events/show.html.erb
<p>Event Name: <%= @event.name %></p>
<p>Description: <%= @event.description %></p>
<p>Category: <%= @event.category_name %></p>
<p>Location: <%= @event.location_name %></p>
<p><%= link_to 'Back to index', events_path %></p>