demo/config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :events do
    collection do
      get :search
      post :search
    end

    member do
      get :dashboard
    end
  end

  resources :events do
    resource :state, :controller => 'event_states'
    resources :attendees, :controller => 'event_attendees'
    resource :location, :controller => 'event_locations'
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  root :to => "welcome#index"

  #So the below routing helper will be admin_events_path or admin_event_path(event)
  namespace :admin do
    resources :events
  end
end

demo/app/controllers/event_locations_controller.rb
class EventLocationsController < ApplicationController
  before_action :find_event

  def show
    @location = @event.location
  end

  def new
    @location = @event.build_location
  end

  def create
    @location = @event.build_location( location_params )
    if @location.save
      redirect_to event_location_url( @event )
    else
      render :action => :new
    end
  end

  def edit
    @location = @event.location
  end

  def update
    @location = @event.location
    if @location.update( location_params )
      redirect_to event_location_url( @event )
    else
      render :action => :edit
    end
  end

  def destroy
    @location = @event.location
    @location.destroy

    redirect_to event_location_url( @event )
  end

  protected

  def find_event
    @event = Event.find(params[:event_id])
  end

  def location_params
    params.require(:location).permit(:name)
  end
end

demo/app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

demo/app/views/event_locations/edit.html.erb
<%= form_for @location, :url => event_location_path(@event), :method \
  => :patch do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

demo/app/views/event_locations/new.html.erb
<%= form_for @location, :url => event_location_path(@event) do |f|%>
  <%= f.text_field :name%>
  <%= f.submit %>
<% end %>

demo/app/views/event_locations/show.html.erb
<h1>
  <%= @event.name %>
</h1>

<% if @event.location %>
  <p><%= @event.location.name %></p>
  <p><%= link_to "edit", edit_event_location_path(@event) %></p>
  <p><%= link_to "destroy", event_location_path(@event), :method =>
  :delete %></p>
<% else %>
  <p>N/A</p>
  <p><%= link_to "Add location", new_event_location_path(@event) %></p>
<% end %>